meta:
  environment: redis-on-dem2-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: just_install_packages
    networks:
      - name: redis_on_dem21

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: redis_on_dem21
  type: manual
  subnets:
  - range: 10.244.9.0/24
    name: redis_on_dem21
    gateway: 10.244.9.1
    static:
      - 10.244.9.2-10.244.9.60
